// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Riwi.Api.Data;

#nullable disable

namespace Riwi.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Riwi.Api.Models.Attendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttendanceId"));

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SessionId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Riwi.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.HasKey("AuditId");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Riwi.Api.Models.CheckinToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TokenId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SessionId");

                    b.ToTable("CheckinTokens");
                });

            modelBuilder.Entity("Riwi.Api.Models.CoderProfile", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CohortId")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.HasIndex("CohortId");

                    b.ToTable("CoderProfiles");
                });

            modelBuilder.Entity("Riwi.Api.Models.Cohort", b =>
                {
                    b.Property<long>("CohortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CohortId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RouteProgramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CohortId");

                    b.HasIndex("RouteProgramId");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("Riwi.Api.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatorPersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresCheckin")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WaitlistLimit")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("CreatorPersonId");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventRequirement", b =>
                {
                    b.Property<long>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequirementId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequirementId");

                    b.HasIndex("EventId");

                    b.ToTable("EventRequirements");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SessionId"));

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("EventId");

                    b.ToTable("EventSessions");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSpeaker", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeakerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("EventId", "SpeakerId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("EventSpeakers");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSurvey", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "TemplateId");

                    b.HasIndex("TemplateId");

                    b.ToTable("EventSurveys");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventTag", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Riwi.Api.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LocationId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Riwi.Api.Models.NotificationLog", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Riwi.Api.Models.Organization", b =>
                {
                    b.Property<long>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrgId"));

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("OrgId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Riwi.Api.Models.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscordHandle")
                        .HasColumnType("text")
                        .HasColumnName("discord_handle");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("PersonId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("people");
                });

            modelBuilder.Entity("Riwi.Api.Models.Registration", b =>
                {
                    b.Property<long>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RegistrationId"));

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("WaitlistPosition")
                        .HasColumnType("integer");

                    b.HasKey("RegistrationId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Riwi.Api.Models.Route", b =>
                {
                    b.Property<long>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProgramId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgramId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Riwi.Api.Models.Speaker", b =>
                {
                    b.Property<long>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SpeakerId"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<long?>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizationOrgId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("SpeakerId");

                    b.HasIndex("OrganizationOrgId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyAnswer", b =>
                {
                    b.Property<long>("ResponseId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.HasKey("ResponseId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyAnswers");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyQuestion", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuestionId"));

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex("TemplateId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyResponse", b =>
                {
                    b.Property<long>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResponseId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("ResponseId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TemplateId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyTemplate", b =>
                {
                    b.Property<long>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TemplateId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("TemplateId");

                    b.ToTable("SurveyTemplates");
                });

            modelBuilder.Entity("Riwi.Api.Models.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Riwi.Api.Models.Attendance", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithMany("Attendances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.EventSession", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId");

                    b.Navigation("Event");

                    b.Navigation("Person");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Riwi.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Riwi.Api.Models.Person", "Actor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Riwi.Api.Models.CheckinToken", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.EventSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Event");

                    b.Navigation("Person");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Riwi.Api.Models.CoderProfile", b =>
                {
                    b.HasOne("Riwi.Api.Models.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId");

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithOne("CoderProfile")
                        .HasForeignKey("Riwi.Api.Models.CoderProfile", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Riwi.Api.Models.Cohort", b =>
                {
                    b.HasOne("Riwi.Api.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteProgramId");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Riwi.Api.Models.Event", b =>
                {
                    b.HasOne("Riwi.Api.Models.Person", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatorPersonId");

                    b.HasOne("Riwi.Api.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId");

                    b.Navigation("Creator");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventRequirement", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSession", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSpeaker", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("EventSpeakers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Speaker", "Speaker")
                        .WithMany("EventSpeakers")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSurvey", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.SurveyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventTag", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Riwi.Api.Models.NotificationLog", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Event");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Riwi.Api.Models.Registration", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithMany("Registrations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Riwi.Api.Models.Speaker", b =>
                {
                    b.HasOne("Riwi.Api.Models.Organization", "Organization")
                        .WithMany("Speakers")
                        .HasForeignKey("OrganizationOrgId");

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithOne("SpeakerProfile")
                        .HasForeignKey("Riwi.Api.Models.Speaker", "PersonId");

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyAnswer", b =>
                {
                    b.HasOne("Riwi.Api.Models.SurveyQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.SurveyResponse", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyQuestion", b =>
                {
                    b.HasOne("Riwi.Api.Models.SurveyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyResponse", b =>
                {
                    b.HasOne("Riwi.Api.Models.Event", "Event")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.Person", "Person")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riwi.Api.Models.SurveyTemplate", "Template")
                        .WithMany("Responses")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Person");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Riwi.Api.Models.Event", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("EventSpeakers");

                    b.Navigation("EventTags");

                    b.Navigation("Registrations");

                    b.Navigation("Sessions");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("Riwi.Api.Models.EventSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Riwi.Api.Models.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Riwi.Api.Models.Organization", b =>
                {
                    b.Navigation("Speakers");
                });

            modelBuilder.Entity("Riwi.Api.Models.Person", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("AuditLogs");

                    b.Navigation("CoderProfile");

                    b.Navigation("CreatedEvents");

                    b.Navigation("Registrations");

                    b.Navigation("SpeakerProfile");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("Riwi.Api.Models.Speaker", b =>
                {
                    b.Navigation("EventSpeakers");
                });

            modelBuilder.Entity("Riwi.Api.Models.SurveyTemplate", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Riwi.Api.Models.Tag", b =>
                {
                    b.Navigation("EventTags");
                });
#pragma warning restore 612, 618
        }
    }
}
